name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install
    - name: find artifacrs
      run: |
          cd /home/runner/work/demo-java-login/demo-java-login/target/
          ls -l
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: my-artifact
        path: /home/runner/work/demo-java-login/demo-java-login/target/dptweb-1.0.war
    
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image: ${{ secrets.IMAGE_NAME }}
    
